from models.all_models import Product

def get_products():
    return [
        Product(id=1, product_name="高保湿リペアヴェール", category=17, brand=24, store_recommend=1, price=1290),
        Product(id=2, product_name="CICA配合お守りベース", category=17, brand=24, store_recommend=1, price=1190),
        Product(id=3, product_name="負担ゼロ・ミネラルシャドウ", category=18, brand=24, store_recommend=1, price=1390),
        Product(id=4, product_name="濃密トリートメント蜜バーム", category=19, brand=24, store_recommend=1, price=990),
        Product(id=5, product_name="薬用プロテクトUVカラー紅", category=19, brand=24, store_recommend=1, price=1090),
        Product(id=6, product_name="トーンアップUV ラベンダーシアー", category=17, brand=21, store_recommend=0, price=990),
        Product(id=7, product_name="水光感グロウプライマー", category=17, brand=21, store_recommend=0, price=1190),
        Product(id=8, product_name="オイルブロック・マットベース", category=17, brand=22, store_recommend=0, price=1090),
        Product(id=9, product_name="スキンスムース・ベージュ", category=17, brand=22, store_recommend=0, price=990),
        Product(id=10, product_name="血色感ピーチアップ下地", category=17, brand=20, store_recommend=0, price=890),
        Product(id=11, product_name="うるおいホイップ・ベース", category=17, brand=20, store_recommend=0, price=990),
        Product(id=12, product_name="ポアレス・シルキー・プライマー", category=17, brand=23, store_recommend=0, price=1290),
        Product(id=13, product_name="コントラスト・トーンアップ", category=17, brand=23, store_recommend=0, price=1190),
        Product(id=14, product_name="さらさらテカリ防止下地", category=17, brand=24, store_recommend=0, price=790),
        Product(id=15, product_name="透明感スノープライマー", category=17, brand=21, store_recommend=0, price=1090),
        Product(id=16, product_name="ときめきマカロンパレット", category=18, brand=20, store_recommend=0, price=1490),
        Product(id=17, product_name="ひだまりデイジーアイズ", category=18, brand=20, store_recommend=0, price=1390),
        Product(id=18, product_name="テラコッタの層パレット", category=18, brand=22, store_recommend=0, price=1490),
        Product(id=19, product_name="スパイスサフランの二色", category=18, brand=22, store_recommend=0, price=1190),
        Product(id=20, product_name="あじさいシアーパレット", category=18, brand=21, store_recommend=0, price=1390),
        Product(id=21, product_name="ミッドナイト・オーシャン", category=18, brand=21, store_recommend=0, price=1490),
        Product(id=22, product_name="アーバン・スレートグレー", category=18, brand=23, store_recommend=0, price=1490),
        Product(id=23, product_name="ニュアンス・グレージュ", category=18, brand=23, store_recommend=0, price=1390),
        Product(id=24, product_name="ジューシーポップ・アイズ", category=18, brand=20, store_recommend=0, price=1190),
        Product(id=25, product_name="ディープ・ロイヤルネイビー", category=18, brand=23, store_recommend=0, price=1490),
        Product(id=26, product_name="こなれカーキの影色パレット", category=18, brand=22, store_recommend=0, price=1390),
        Product(id=27, product_name="うるおい珊瑚の粘膜ティント", category=19, brand=20, store_recommend=0, price=1090),
        Product(id=28, product_name="チューリップ・シュガー・グロス", category=19, brand=20, store_recommend=0, price=890),
        Product(id=29, product_name="レンガ色の熟成ルージュ", category=19, brand=22, store_recommend=0, price=1190),
        Product(id=30, product_name="こなれパンプキン・ハニー", category=19, brand=22, store_recommend=0, price=1090),
        Product(id=31, product_name="桜貝のシアーリップ", category=19, brand=21, store_recommend=0, price=990),
        Product(id=32, product_name="木苺口紅", category=19, brand=21, store_recommend=0, price=1090),
        Product(id=33, product_name="冬の女王・ベルベットリップ", category=19, brand=23, store_recommend=0, price=1390),
        Product(id=34, product_name="大人のボルドー・ステイン", category=19, brand=23, store_recommend=0, price=1290),
        Product(id=35, product_name="都会的メタリック・ローズ", category=19, brand=23, store_recommend=0, price=1490),
        Product(id=36, product_name="ラムネソーダのきらめきグロス", category=19, brand=20, store_recommend=0, price=890),
    ]